/** Word pools organized by theme, suitable for kids ages 5–10. */

export const themes: Record<string, string[]> = {
  Animals: [
    "ant", "bat", "bear", "bee", "bird", "bull", "calf", "cat", "chick", "clam",
    "cod", "colt", "cow", "crab", "crow", "deer", "dog", "dolphin", "dove", "duck",
    "eagle", "eel", "elk", "emu", "ewe", "falcon", "fawn", "finch", "fish", "flea",
    "fly", "foal", "fox", "frog", "goat", "goose", "gull", "hare", "hawk", "hen",
    "heron", "horse", "jay", "kitten", "lamb", "lark", "lion", "llama", "lobster", "lynx",
    "mare", "mink", "mole", "moose", "moth", "mouse", "mule", "newt", "orca", "otter",
    "owl", "ox", "panda", "parrot", "perch", "pig", "pike", "pony", "puma", "puppy",
    "quail", "rabbit", "ram", "rat", "raven", "robin", "seal", "shark", "sheep", "skunk",
    "slug", "snail", "snake", "squid", "stork", "swan", "tiger", "toad", "trout", "tuna",
    "turkey", "turtle", "viper", "wasp", "whale", "wolf", "worm", "wren", "yak", "zebra",
    "badger", "beaver", "bison", "camel", "cobra", "coral", "crane", "dingo", "egret", "ferret",
    "gecko", "gerbil", "gibbon", "gorilla", "grouse", "hamster", "hippo", "hornet", "hyena", "iguana",
    "impala", "jackal", "jaguar", "koala", "lemur", "leopard", "lizard", "macaw", "mantis", "marlin",
    "marten", "monkey", "osprey", "panther", "parrot", "pelican", "penguin", "pigeon", "python", "salmon",
    "shrimp", "spider", "toucan", "walrus", "weasel", "wombat", "donkey", "coyote", "falcon", "magpie",
  ],
  Plants: [
    "aloe", "basil", "bean", "birch", "bloom", "bud", "bulb", "bush", "cactus", "cedar",
    "clover", "corn", "daisy", "elm", "fern", "fig", "flax", "flora", "flower", "fruit",
    "garden", "ginger", "grain", "grape", "grass", "green", "grove", "hedge", "herb", "holly",
    "iris", "ivy", "kelp", "kale", "laurel", "leaf", "lichen", "lilac", "lily", "lime",
    "lotus", "maple", "melon", "mint", "moss", "myrtle", "nettle", "oak", "olive", "onion",
    "orchid", "palm", "pansy", "peach", "pear", "peony", "petal", "pine", "plum", "pollen",
    "poppy", "reed", "root", "rose", "sage", "seed", "shrub", "soil", "sprout", "stem",
    "stump", "thorn", "thyme", "tree", "tulip", "vine", "violet", "weed", "wheat", "willow",
    "yarrow", "yew", "zinnia", "aster", "bark", "berry", "blossom", "branch", "briar", "catnip",
    "cherry", "chive", "clove", "cotton", "dill", "fennel", "ficus", "ginkgo", "hazel", "hemlock",
    "hosta", "jasmine", "juniper", "lemon", "mango", "marigold", "nutmeg", "parsley", "pepper", "pumpkin",
    "radish", "redwood", "rosemary", "saffron", "sequoia", "spinach", "spruce", "squash", "tomato", "turnip",
    "walnut", "bamboo", "acacia", "azalea", "begonia", "cypress", "dahlia", "hickory", "lavender", "magnolia",
  ],
  Ocean: [
    "anchor", "bay", "beach", "boat", "buoy", "cape", "coast", "coral", "cove", "crab",
    "crest", "current", "deep", "depth", "dive", "dock", "drift", "dune", "ebb", "fin",
    "fish", "float", "flood", "flow", "foam", "gulf", "harbor", "hull", "ice", "inlet",
    "island", "kelp", "knot", "lagoon", "lake", "mast", "net", "ocean", "paddle", "pearl",
    "pier", "plank", "pod", "port", "reef", "rift", "ripple", "river", "rock", "rope",
    "sail", "salt", "sand", "sea", "seagull", "seal", "seaweed", "shell", "ship", "shore",
    "shrimp", "splash", "spray", "squid", "star", "stern", "storm", "stream", "surf", "swell",
    "swim", "tide", "trawl", "trench", "vessel", "voyage", "wade", "water", "wave", "whale",
    "wharf", "wind", "wreck", "abyss", "algae", "atoll", "barge", "bluff", "canoe", "cargo",
    "cavern", "clam", "cliff", "cruise", "delta", "fjord", "fleet", "galley", "geyser", "grotto",
    "harbor", "jetty", "kayak", "keel", "marsh", "mussel", "narwhal", "nautical", "octopus", "oyster",
    "pelican", "penguin", "plankton", "riptide", "rudder", "sailor", "sandbar", "scallop", "seahorse", "shipwreck",
    "snorkel", "starfish", "stingray", "sturgeon", "surfing", "torpedo", "trident", "tugboat", "undercurrent", "walrus",
  ],
  Space: [
    "alien", "arc", "ash", "atom", "axis", "beam", "belt", "black", "blast", "blaze",
    "bolt", "burst", "cloud", "comet", "core", "cosmic", "crater", "dawn", "deep", "disk",
    "drift", "dusk", "dust", "dwarf", "earth", "eclipse", "energy", "flare", "flash", "float",
    "fog", "force", "fuel", "galaxy", "gas", "giant", "glow", "gravity", "halo", "heat",
    "ice", "ion", "jet", "jolt", "launch", "lens", "light", "lunar", "mars", "mass",
    "matter", "mercury", "meteor", "milky", "moon", "nebula", "neptune", "nova", "orbit", "outer",
    "phase", "planet", "pluto", "probe", "pulse", "quasar", "radar", "ray", "red", "ring",
    "rock", "rocket", "rover", "sail", "saturn", "shaft", "sky", "solar", "space", "spark",
    "spin", "star", "sun", "tail", "titan", "trail", "uranus", "vast", "venus", "void",
    "warp", "wave", "white", "wind", "zoom", "zenith", "plasma", "photon", "prism", "sphere",
    "shuttle", "signal", "capsule", "mission", "station", "cosmic", "stellar", "horizon", "asteroid", "starship",
    "sunspot", "aurora", "cluster", "equinox", "fireball", "pulsar", "radiant", "stardust", "sunrise", "sunset",
    "telluric", "twilight", "universe", "voyager", "wormhole", "zenith", "asteroid", "constellation", "satellite", "telescope",
  ],
  Food: [
    "apple", "bacon", "bagel", "bake", "basil", "bean", "beef", "beet", "berry", "bite",
    "blend", "boil", "bowl", "bread", "broil", "broth", "brownie", "bun", "butter", "cake",
    "candy", "carrot", "celery", "cheese", "cherry", "chili", "chip", "chop", "chow", "cider",
    "clam", "cobbler", "cocoa", "cookie", "corn", "cream", "crisp", "crust", "cube", "curry",
    "date", "dice", "dip", "dish", "donut", "dough", "dumpling", "feast", "fig", "fillet",
    "flour", "fork", "fries", "frost", "fruit", "fudge", "garlic", "glaze", "grain", "grape",
    "gravy", "grill", "grits", "guava", "ham", "hash", "heat", "herb", "honey", "jam",
    "jelly", "jerky", "juice", "kale", "ketchup", "lemon", "lentil", "lettuce", "lime", "loaf",
    "mango", "maple", "meal", "melon", "milk", "mint", "mochi", "muffin", "nacho", "noodle",
    "nut", "oat", "olive", "onion", "orange", "pancake", "pasta", "peach", "peanut", "pear",
    "pepper", "pickle", "pie", "pizza", "plum", "pop", "potato", "pretzel", "prune", "pudding",
    "raisin", "ranch", "rice", "roast", "roll", "salad", "salt", "sauce", "scone", "snack",
    "soup", "spice", "steak", "stew", "sugar", "syrup", "taco", "toast", "tomato", "torte",
    "treat", "waffle", "walnut", "wheat", "wrap", "yam", "yogurt", "zest", "almond", "apricot",
  ],
  Colors: [
    "amber", "aqua", "azure", "beige", "black", "blue", "blush", "bone", "brass", "brick",
    "bronze", "brown", "buff", "burgundy", "camel", "canary", "caramel", "cardinal", "carmine", "cedar",
    "cerise", "charcoal", "cherry", "chestnut", "cinnamon", "citron", "coal", "cobalt", "cocoa", "coffee",
    "copper", "coral", "corn", "cranberry", "cream", "crimson", "crystal", "cyan", "daffodil", "desert",
    "denim", "dusk", "ebony", "ecru", "eggplant", "emerald", "fawn", "flame", "flax", "forest",
    "frost", "fuchsia", "garnet", "ginger", "gold", "grape", "gray", "green", "hazel", "heather",
    "honey", "hunter", "ice", "indigo", "iron", "ivory", "jade", "jet", "khaki", "lavender",
    "lemon", "lilac", "lime", "linen", "magenta", "mahogany", "mango", "maple", "marigold", "maroon",
    "mauve", "melon", "midnight", "mint", "mocha", "moss", "mustard", "navy", "nutmeg", "ocher",
    "olive", "onyx", "opal", "orange", "orchid", "oyster", "papaya", "peach", "pearl", "pepper",
    "pine", "pink", "plum", "poppy", "powder", "pumpkin", "purple", "quartz", "raisin", "raspberry",
    "red", "rose", "ruby", "rust", "saffron", "sage", "salmon", "sand", "sapphire", "scarlet",
    "sienna", "silver", "sky", "slate", "smoke", "snow", "steel", "stone", "straw", "sunset",
    "tan", "tangerine", "teal", "thistle", "topaz", "turquoise", "umber", "vanilla", "violet", "walnut",
    "wheat", "white", "wine", "yellow",
  ],
  Weather: [
    "air", "arc", "arid", "aurora", "balmy", "blast", "blaze", "blizzard", "blow", "bolt",
    "breeze", "bright", "brisk", "calm", "chill", "clear", "climate", "cloud", "cold", "cool",
    "crisp", "cyclone", "damp", "dawn", "degree", "deluge", "dew", "downpour", "draft", "drizzle",
    "drought", "dry", "dusk", "dust", "flood", "flurry", "fog", "freeze", "fresh", "front",
    "frost", "gale", "glow", "gust", "hail", "haze", "heat", "hot", "humid", "ice",
    "lightning", "mild", "mist", "monsoon", "muggy", "overcast", "pour", "puddle", "rain", "rainbow",
    "shower", "sky", "sleet", "slush", "smog", "snow", "squall", "steam", "storm", "sun",
    "sunny", "surge", "tempest", "thaw", "thunder", "tornado", "tropic", "typhoon", "warm", "wave",
    "wet", "whirl", "wind", "winter", "blanket", "celsius", "chinook", "cirrus", "coastal", "cumulus",
    "drenched", "equinox", "foggy", "freezing", "glacier", "gusty", "harvest", "icicle", "jetstream", "marine",
    "nimbus", "norther", "polar", "raindrop", "rainy", "season", "shelter", "sizzle", "snowfall", "solstice",
    "spring", "stratus", "sultry", "summer", "sunrise", "sunset", "thermal", "tropical", "turbulent", "umbrella",
    "vapor", "vortex", "warming", "weather", "westerly", "windy", "winter", "zephyr",
  ],
  Sports: [
    "ace", "arch", "ball", "base", "basket", "bat", "block", "boat", "bowl", "box",
    "catch", "chase", "cheer", "climb", "coach", "cone", "court", "crew", "cross", "cup",
    "dart", "dash", "deck", "dive", "dodge", "draft", "dribble", "drive", "drop", "dunk",
    "fan", "fence", "field", "flip", "fly", "foul", "fumble", "game", "goal", "golf",
    "grip", "gym", "hike", "hit", "hockey", "hook", "hoop", "hurdle", "ice", "jab",
    "javelin", "jersey", "jog", "jump", "kayak", "kick", "lap", "lead", "league", "lift",
    "lob", "lose", "lunge", "match", "medal", "meet", "net", "oar", "pace", "paddle",
    "pass", "pitch", "play", "point", "pole", "polo", "pool", "puck", "pull", "punt",
    "push", "race", "rack", "rally", "record", "ref", "relay", "ride", "ring", "row",
    "rugby", "run", "rush", "save", "score", "serve", "shot", "skate", "ski", "slam",
    "slice", "slide", "snap", "soccer", "spin", "sprint", "squad", "start", "steal", "step",
    "stick", "stop", "strike", "stroke", "surf", "swim", "swing", "tag", "team", "throw",
    "toss", "track", "trail", "trap", "vault", "volley", "walk", "water", "win", "yoga",
    "sprint", "trophy", "umpire", "whistle", "amateur", "captain", "doubles", "fitness", "goalie", "inning",
  ],
  Music: [
    "alto", "aria", "band", "banjo", "bass", "beat", "bell", "blues", "bongo", "bow",
    "brass", "bugle", "carol", "cello", "choir", "chord", "clap", "clef", "dance", "drum",
    "duet", "echo", "fiddle", "fife", "flat", "flute", "folk", "forte", "gig", "glee",
    "gong", "groove", "guitar", "harp", "harmony", "horn", "hymn", "jazz", "jingle", "key",
    "lilt", "lute", "lyre", "march", "melody", "mix", "mood", "mute", "note", "oboe",
    "octave", "opera", "organ", "pause", "piano", "pick", "pipe", "pitch", "play", "pluck",
    "polka", "pop", "pulse", "rap", "reed", "rest", "rhythm", "riff", "ring", "rock",
    "roll", "scale", "sharp", "sing", "snap", "solo", "song", "sonic", "soul", "sound",
    "strum", "sway", "swing", "tempo", "tenor", "tone", "trio", "tuba", "tune", "vibe",
    "viola", "vocal", "waltz", "wind", "chant", "chorus", "cymbal", "encore", "fanfare", "lyric",
    "maracas", "medley", "metronome", "musical", "overture", "prelude", "quartet", "refrain", "serenade", "soprano",
    "staccato", "symphony", "tambourine", "timpani", "tremolo", "trumpet", "ukulele", "vibrato", "virtuoso", "xylophone",
  ],
  School: [
    "add", "art", "bell", "board", "book", "bus", "chalk", "chart", "class", "clock",
    "club", "coach", "count", "craft", "crayon", "desk", "draw", "drill", "edit", "erase",
    "essay", "exam", "fact", "flag", "folder", "font", "form", "globe", "grade", "graph",
    "group", "gym", "hall", "ink", "lab", "learn", "lens", "lesson", "letter", "library",
    "line", "list", "locker", "lunch", "map", "marker", "math", "mural", "note", "number",
    "office", "page", "paint", "paper", "paste", "pen", "pencil", "plan", "play", "poem",
    "point", "print", "prize", "project", "pupil", "quiz", "read", "recess", "report", "ring",
    "ruler", "school", "score", "seat", "shelf", "skill", "slate", "snack", "spell", "sport",
    "staff", "stage", "stamp", "star", "study", "sum", "table", "tape", "teach", "team",
    "term", "test", "text", "tidy", "tool", "trace", "tutor", "type", "unit", "vote",
    "word", "write", "year", "zone", "absent", "answer", "binder", "campus", "chapter", "college",
    "compass", "correct", "diploma", "eraser", "faculty", "history", "homework", "journal", "lecture", "mentor",
    "notebook", "palette", "planner", "problem", "program", "reading", "scholar", "science", "student", "subject",
  ],
  Dinosaurs: [
    "amber", "armor", "beak", "bone", "brute", "burrow", "claw", "coil", "crest", "dig",
    "dust", "egg", "era", "evolve", "extinct", "fang", "feather", "femur", "fin", "flock",
    "foot", "forest", "fossil", "giant", "graze", "growl", "guard", "hatch", "herd", "horn",
    "hunt", "jaw", "jolt", "jungle", "lair", "lake", "land", "lizard", "lunge", "marsh",
    "mega", "meteor", "mighty", "molar", "mound", "mud", "muscle", "nest", "old", "pack",
    "paw", "peak", "plod", "plume", "pond", "prey", "primal", "prowl", "quake", "raptor",
    "reign", "rib", "ridge", "roam", "roar", "rock", "ruin", "scale", "scrape", "shell",
    "shrub", "size", "skeleton", "skull", "slope", "snout", "spike", "spine", "stomp", "stone",
    "stump", "swamp", "tail", "talon", "teeth", "terrain", "thud", "titan", "tooth", "trace",
    "track", "trait", "trap", "tread", "trench", "tundra", "tusk", "valley", "vast", "venom",
    "volcano", "wander", "wild", "wing", "burrow", "carnivore", "cavern", "creature", "defense", "dinosaur",
    "discover", "enormous", "footprint", "herbivore", "jurassic", "massive", "predator", "preserve", "pterosaur", "reptile",
    "skeleton", "stampede", "survive", "triassic", "tropical",
  ],
  Seasons: [
    "acorn", "apple", "autumn", "bask", "beach", "blanket", "bloom", "blossom", "blush", "breeze",
    "bright", "bud", "bundle", "burn", "bush", "calm", "candle", "cape", "carol", "chill",
    "chilly", "chirp", "cider", "cloak", "coast", "cocoa", "cozy", "crisp", "crop", "crunch",
    "dawn", "dew", "drift", "dry", "dusk", "fall", "feast", "fire", "flock", "flurry",
    "fog", "freeze", "fresh", "frost", "fruit", "gale", "garden", "gather", "glow", "golden",
    "grain", "green", "grow", "gust", "hail", "harvest", "hay", "heat", "hibernate", "holly",
    "hot", "husk", "ice", "icicle", "ivy", "joy", "jump", "lake", "lawn", "leaf",
    "light", "melt", "migrate", "mist", "moon", "moss", "mulch", "nest", "nip", "nut",
    "oat", "orange", "parade", "petal", "picnic", "pile", "pine", "plant", "play", "pluck",
    "plum", "pool", "puddle", "pumpkin", "rain", "rake", "red", "rest", "ripe", "river",
    "scarf", "seed", "shade", "shed", "shine", "shovel", "sled", "sleet", "slush", "snow",
    "snug", "soil", "splash", "spring", "sprout", "stew", "stir", "storm", "straw", "summer",
    "sun", "swim", "thaw", "tint", "toast", "trail", "tree", "tulip", "vine", "warm",
    "wave", "wind", "winter", "woolly", "yard",
  ],
  Bugs: [
    "ant", "aphid", "bee", "beetle", "bite", "bloom", "bug", "burrow", "buzz", "caterpillar",
    "centipede", "chirp", "chrysalis", "cicada", "climb", "cocoon", "colony", "cricket", "critter", "crow",
    "dart", "dig", "dirt", "dragonfly", "drone", "dung", "earwig", "egg", "feeler", "firefly",
    "flea", "flight", "flutter", "fly", "forage", "garden", "glow", "gnat", "gnaw", "grass",
    "grub", "hatch", "hive", "hop", "hornet", "host", "hover", "hum", "inch", "insect",
    "jumper", "larva", "leaf", "legs", "lice", "log", "louse", "maggot", "mandible", "mantis",
    "midge", "mite", "monarch", "mosquito", "moth", "mud", "nectar", "nest", "nit", "nymph",
    "petal", "pill", "pinch", "plant", "pod", "pollen", "pond", "pupa", "queen", "roly",
    "roach", "rose", "rover", "sawfly", "scale", "shell", "silk", "slug", "snail", "soil",
    "spider", "spin", "sting", "stink", "swarm", "termite", "thorax", "thrip", "tick", "twig",
    "wasp", "web", "weevil", "wing", "worm", "abdomen", "antenna", "beehive", "beeswax", "bumblebee",
    "butterfly", "camouflage", "compound", "crawl", "cricket", "darner", "emerald", "exoskeleton", "firefly", "flutter",
    "grasshopper", "honeybee", "katydid", "ladybug", "larva", "metamorphosis", "millipede", "pollinate", "stinger", "thorax",
  ],
  Vehicles: [
    "auto", "axle", "bike", "blade", "boat", "bolt", "brake", "bumper", "bus", "cab",
    "canoe", "cargo", "cart", "chain", "clutch", "coupe", "crane", "cruise", "cycle", "dash",
    "deck", "diesel", "dirt", "dock", "door", "drag", "drift", "drive", "drum", "dump",
    "engine", "exhaust", "express", "ferry", "fender", "flat", "fleet", "float", "fly", "frame",
    "freight", "fuel", "gas", "gauge", "gear", "glide", "gondola", "gravel", "grip", "haul",
    "helm", "hood", "horn", "hull", "hybrid", "jeep", "jet", "kayak", "keel", "lane",
    "lever", "lift", "limo", "link", "load", "lock", "mast", "metro", "mile", "mini",
    "motor", "muffler", "oar", "paddle", "park", "path", "pedal", "pier", "pilot", "pipe",
    "plane", "platform", "plow", "port", "power", "propel", "pump", "race", "rack", "raft",
    "rail", "ramp", "ride", "road", "rocket", "rotor", "route", "rudder", "runway", "rush",
    "sail", "sedan", "semi", "ship", "shuttle", "signal", "skid", "sled", "speed", "spoke",
    "steer", "stern", "stop", "subway", "tanker", "taxi", "tire", "tow", "track", "tractor",
    "trailer", "train", "tram", "truck", "trunk", "turbo", "turn", "van", "vessel", "wagon",
    "wheel", "yacht", "zone",
  ],
  Fantasy: [
    "amulet", "archer", "armor", "arrow", "axe", "banner", "blade", "bolt", "bow", "brew",
    "cape", "castle", "cauldron", "cave", "charm", "chest", "cloak", "coin", "crown", "crystal",
    "curse", "dagger", "dark", "dawn", "dome", "doom", "dragon", "dream", "drift", "dungeon",
    "dusk", "dwarf", "elder", "elf", "ember", "enchant", "epic", "fairy", "fang", "fate",
    "feast", "flame", "flash", "flight", "forge", "fort", "frost", "gate", "gem", "ghost",
    "giant", "glyph", "gnome", "goblin", "gold", "golem", "guard", "guild", "halo", "hawk",
    "heal", "helm", "hero", "hilt", "hood", "horn", "hydra", "idol", "imp", "jade",
    "jewel", "joust", "keep", "king", "knight", "lance", "legend", "light", "lore", "luck",
    "mace", "magic", "manor", "maze", "might", "mirror", "moat", "moon", "myth", "noble",
    "orc", "orb", "pegasus", "phantom", "phoenix", "pixie", "potion", "prince", "princess", "quest",
    "realm", "riddle", "ring", "robe", "rogue", "rune", "sage", "scar", "scroll", "shadow",
    "shield", "shrine", "skull", "sorcerer", "spark", "spell", "spirit", "sprite", "staff", "steed",
    "stone", "storm", "sword", "throne", "titan", "tomb", "tower", "troll", "unicorn", "vale",
    "valor", "vampire", "vault", "wand", "ward", "warrior", "warlock", "werewolf", "wings", "witch",
    "wizard", "wraith", "wyrm",
  ],
  Geography: [
    "alps", "arch", "atoll", "bank", "basin", "bay", "beach", "bluff", "bog", "brook",
    "butte", "canal", "canyon", "cape", "cave", "cavern", "city", "cliff", "coast", "coral",
    "county", "creek", "crest", "dale", "dam", "delta", "dune", "east", "falls", "fault",
    "fen", "field", "fjord", "flat", "ford", "forest", "geyser", "glacier", "glen", "gorge",
    "grove", "gulf", "gully", "harbor", "heath", "hill", "hollow", "inlet", "island", "isle",
    "knoll", "lagoon", "lake", "land", "ledge", "levee", "marsh", "mesa", "moor", "mount",
    "north", "oasis", "ocean", "park", "pass", "path", "peak", "pier", "plain", "plateau",
    "point", "pond", "port", "prairie", "range", "ravine", "reef", "ridge", "rift", "river",
    "road", "rock", "sand", "shore", "slope", "south", "spring", "strait", "stream", "summit",
    "swamp", "terrace", "tide", "trail", "trench", "tundra", "vale", "valley", "volcano", "west",
    "bluff", "channel", "continent", "country", "desert", "equator", "estuary", "foothills", "grassland", "hemisphere",
    "highland", "iceberg", "isthmus", "landmark", "lowland", "mainland", "mountain", "peninsula", "rainforest", "savanna",
    "seashore", "steppe", "tributary", "tropical", "waterfall", "wetland",
  ],
  Clothing: [
    "apron", "band", "belt", "beret", "blazer", "blouse", "bonnet", "boot", "bow", "braid",
    "buckle", "button", "cap", "cape", "cardigan", "clasp", "cloak", "cloth", "coat", "collar",
    "corset", "cotton", "cuff", "denim", "dress", "drape", "fabric", "felt", "fiber", "flannel",
    "fleece", "fold", "frill", "fringe", "frock", "fur", "garter", "gown", "hat", "heel",
    "hem", "hood", "hose", "jacket", "jean", "jersey", "jewel", "jumper", "khaki", "knit",
    "lace", "layer", "leather", "linen", "loop", "mitten", "moccasin", "muff", "nylon", "outfit",
    "oxford", "pad", "pants", "patch", "pattern", "plaid", "pleat", "pocket", "polo", "poncho",
    "purse", "robe", "ruffle", "sandal", "sari", "sash", "satin", "scarf", "seam", "shawl",
    "shirt", "shoe", "shorts", "silk", "skirt", "sleeve", "slipper", "smock", "snap", "sneaker",
    "sock", "stitch", "stole", "strap", "stripe", "suit", "sweater", "taffeta", "tailor", "thread",
    "tie", "tights", "top", "trim", "tunic", "tweed", "uniform", "velvet", "vest", "visor",
    "wear", "wig", "wool", "wrap", "yarn", "zipper",
  ],
  Pets: [
    "adopt", "bark", "bath", "beak", "bed", "bell", "bird", "bone", "bowl", "breed",
    "brush", "budgie", "bunny", "cage", "canary", "care", "cat", "chase", "chew", "chin",
    "chirp", "claw", "clean", "coat", "collar", "comb", "cozy", "cuddle", "cute", "den",
    "diet", "dig", "dog", "dome", "drink", "ear", "eat", "farm", "feast", "feed",
    "fetch", "fin", "fish", "flea", "fluff", "food", "friend", "fur", "gecko", "gentle",
    "gerbil", "glow", "gnaw", "goldfish", "groom", "guard", "guinea", "hamster", "happy", "hay",
    "hide", "home", "hop", "hug", "hutch", "iguana", "jaw", "kennel", "kitten", "lap",
    "lead", "leash", "lick", "litter", "lizard", "love", "loyal", "mane", "mouse", "muzzle",
    "nest", "newt", "nose", "nuzzle", "obey", "pant", "parrot", "paw", "perch", "pet",
    "play", "plume", "pony", "poodle", "pooch", "pounce", "pup", "puppy", "purr", "rabbit",
    "rescue", "ribbon", "roam", "run", "scale", "shed", "shelter", "sit", "sleep", "sniff",
    "snuggle", "splash", "spot", "stall", "stroke", "swim", "tag", "tail", "tank", "tongue",
    "toy", "train", "treat", "trick", "trim", "trot", "tummy", "turtle", "vet", "wag",
    "walk", "water", "whisker", "wing", "yawn", "yip",
  ],
  Nature: [
    "acorn", "bark", "bay", "bloom", "bluff", "bog", "boulder", "branch", "breeze", "brook",
    "brush", "bush", "canyon", "cave", "cliff", "cloud", "coast", "creek", "dale", "dawn",
    "delta", "den", "desert", "dew", "dirt", "drift", "drip", "dune", "dusk", "dust",
    "earth", "echo", "edge", "ember", "falls", "fern", "field", "fire", "flame", "flora",
    "flow", "fog", "forest", "frost", "gale", "garden", "glen", "gorge", "grain", "grass",
    "grove", "gust", "hail", "harbor", "heath", "hedge", "hill", "hollow", "horizon", "ice",
    "inlet", "island", "ivy", "knoll", "lagoon", "lake", "land", "leaf", "ledge", "lichen",
    "light", "log", "marsh", "meadow", "mesa", "mist", "moor", "moss", "mound", "mud",
    "oak", "ocean", "outcrop", "pebble", "peak", "pine", "plain", "plateau", "pollen", "pond",
    "prairie", "rain", "ravine", "reef", "ridge", "rift", "ripple", "river", "rock", "root",
    "sand", "shore", "sky", "slope", "snow", "soil", "spring", "star", "stone", "storm",
    "stream", "sun", "surge", "swamp", "thicket", "thorn", "thunder", "tide", "timber", "trail",
    "tree", "trunk", "tundra", "vale", "valley", "vine", "volcano", "water", "wave", "wetland",
    "wild", "willow", "wind", "wood",
  ],
  Camping: [
    "ash", "axe", "badge", "bait", "bark", "bear", "bedroll", "berth", "blaze", "bonfire",
    "boot", "brush", "bucket", "cabin", "camp", "candle", "canoe", "cliff", "coal", "compass",
    "cone", "cook", "cooler", "cord", "cot", "creek", "dawn", "den", "dirt", "duck",
    "dusk", "ember", "explore", "fauna", "fern", "fire", "fish", "flag", "flame", "flask",
    "flint", "flora", "foam", "forest", "fork", "fuel", "gear", "glow", "gorge", "grill",
    "grove", "guide", "hatch", "heat", "hike", "hill", "hollow", "hook", "hoot", "inlet",
    "kayak", "kettle", "kindle", "knapsack", "knot", "lake", "lamp", "lantern", "lean", "log",
    "loop", "map", "marsh", "match", "moon", "moss", "mount", "mud", "mug", "nature",
    "nest", "night", "noon", "north", "oar", "outdoor", "owl", "pack", "paddle", "path",
    "peak", "pine", "pitch", "pond", "ranger", "rapids", "rest", "ridge", "river", "road",
    "rock", "rope", "roost", "sack", "shade", "shelter", "shore", "site", "sleep", "slope",
    "smoke", "snack", "soil", "spark", "spring", "star", "stew", "stick", "stone", "stove",
    "stream", "stump", "sun", "tent", "thermos", "tinder", "torch", "trail", "tree", "trout",
    "trunk", "valley", "vista", "water", "wild", "wood", "yarn",
  ],
};

/** Every word across all themes, deduplicated. */
export function getAllWords(): string[] {
  const set = new Set<string>();
  for (const pool of Object.values(themes)) {
    for (const w of pool) {
      set.add(w.toUpperCase());
    }
  }
  return Array.from(set);
}

/** Get words for a specific theme, all upper-cased. */
export function getThemeWords(theme: string): string[] {
  if (theme === "Random") {
    return getAllWords();
  }
  const pool = themes[theme];
  if (!pool) return getAllWords();
  return pool.map(w => w.toUpperCase());
}

/** All available theme names including "Random". */
export const themeNames: string[] = [...Object.keys(themes), "Random"];
